apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnmgte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nnmgte
  template:
    metadata:
      labels:
        app: nnmgte
    spec:
      containers:
      - image: okteto.dev/nnmgte:latest
        name: nnmgte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2de8fff0-2dad-4691-972a-5280356e760c"
        - name: Vless_Path
          value: "/vlanlyfhDER"
        - name: Vmess_UUID
          value: "2de8fff0-2dad-4691-972a-5280356e760c"
        - name: Vmess_Path
          value: "/vmEoawerh"
        - name: Share_Path
          value: "/v2link"
