apiVersion: v1
kind: Service
metadata:
  name: nnmgte
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "nnmgte"
    port: 8080
  selector:
    app: nnmgte
